import type { RescueDefinition } from "./rescue";

/**
 * Catalog of rescue mini-missions. One or more rescues per main mission, keyed
 * to the phase a player is stuck on. Every phase of every field mission must be
 * covered (enforced by lib/rescues.test.ts). Each mission has one `isDefault`
 * rescue used when no phase matches.
 */
export const RESCUES: RescueDefinition[] = [
  // ─── VLAN That Vanished ────────────────────────────────────────────────────
  {
    id: "rescue-vlan-trunk",
    mission: "vlan",
    phases: [],
    isDefault: true,
    title: "The trunk & allowed VLANs",
    teaches: "What a trunk is, and the one command that fixes the missing VLAN.",
    tip: "Back in the mission: on SW1 enter interface g0/1, then type switchport trunk allowed vlan add 20.",
    steps: [
      {
        kind: "explain",
        title: "One highway, many lanes",
        body: "A trunk is the link between two switches. Unlike an access port (one VLAN, one end device), a trunk carries many VLANs at once. Every frame gets an 802.1Q tag so the far switch knows which VLAN it belongs to — and a trunk only carries the VLANs on its allowed list.",
      },
      {
        kind: "checkpoint",
        title: "Which link is a trunk?",
        prompt: "PC-Sales connects to SW1, and SW1 connects to SW2. Which kind of link should carry VLAN 10 and VLAN 20 between the two switches?",
        options: [
          { value: "trunk", title: "A trunk between SW1 and SW2", note: "Carries many VLANs, tagged with 802.1Q" },
          { value: "access", title: "An access port to PC-Sales", note: "One VLAN, one end device" },
          { value: "mgmt", title: "The management port", note: "Out-of-band device management" },
        ],
        correct: "trunk",
        explain: "Trunks connect switches and carry many VLANs; access ports serve single end devices.",
        wrongGuidance: "Think about the link BETWEEN switches — that is where many VLANs need to travel at once.",
      },
      {
        kind: "cli",
        device: "SW1",
        prompt: "SW1(config-if)#",
        title: "Add VLAN 20 to the trunk",
        command: "switchport trunk allowed vlan add 20",
        expectedOutput: "VLAN 20 added to the allowed VLAN list.",
        wrongHint: "You are on interface Gi0/1 in config mode — type: switchport trunk allowed vlan add 20",
        explain: "VLAN 20 is now on the trunk's allowed list, so Sales traffic can cross to the gateway.",
      },
    ],
  },

  // ─── STP Storm ─────────────────────────────────────────────────────────────
  {
    id: "rescue-stp-root",
    mission: "stp",
    phases: ["root_election"],
    isDefault: false,
    title: "Who becomes root?",
    teaches: "Bridge ID = priority + MAC, and the lowest one wins root election.",
    tip: "Compare bridge IDs before choosing: 24577 beats 32769, so SW2 becomes root.",
    steps: [
      {
        kind: "explain",
        title: "Bridge ID = priority + MAC",
        body: "Every switch has a bridge ID: its priority (32768 by default) plus its MAC address. The switch with the LOWEST bridge ID becomes the spanning-tree root, and every other switch computes its path toward the root.",
      },
      {
        kind: "checkpoint",
        title: "Pick the root",
        prompt: "SW1 has bridge ID 32769 and SW2 has bridge ID 24577. Which switch becomes root?",
        options: [
          { value: "sw2", title: "SW2 — lower bridge ID", note: "24577 < 32769, so SW2 wins" },
          { value: "sw1", title: "SW1 — higher bridge ID", note: "32769 is larger, so SW1 loses" },
          { value: "tie", title: "Tie — they negotiate", note: "Bridge IDs are different, no tie here" },
        ],
        correct: "sw2",
        explain: "SW2's 24577 is lower than SW1's 32769 — the lowest bridge ID wins root election.",
        wrongGuidance: "Bridge ID = priority + MAC, and LOWER wins. Compare the two numbers: which one is smaller?",
      },
      {
        kind: "explain",
        title: "Remember for the mission",
        body: "When the mission asks 'who becomes root?', read the bridge IDs and pick the lowest. Nothing else matters at election time.",
      },
    ],
  },
  {
    id: "rescue-stp-guards",
    mission: "stp",
    phases: ["bpdu_guard", "root_guard"],
    isDefault: true,
    title: "Guards: edge vs. root",
    teaches: "BPDU Guard protects edge ports; Root Guard protects designated uplinks from being hijacked.",
    tip: "Edge port + surprise BPDU = BPDU Guard. Designated uplink + superior root claim = Root Guard.",
    steps: [
      {
        kind: "explain",
        title: "Two guards, two jobs",
        body: "BPDU Guard sits on edge/access ports where only end devices should connect — if a BPDU arrives (someone plugged in a switch), the port err-disables instantly. Root Guard sits on designated ports facing other switches that must never become root — it ignores superior BPDUs instead of letting them change the root.",
      },
      {
        kind: "checkpoint",
        title: "The rogue switch",
        prompt: "A user plugged a switch into access port Gi0/5 and it is sending BPDUs. Which feature locks the port down?",
        options: [
          { value: "bpdu-guard", title: "BPDU Guard", note: "Err-disables the edge port on unexpected BPDUs" },
          { value: "root-guard", title: "Root Guard", note: "For designated uplinks, not edge ports" },
          { value: "loop-guard", title: "Loop Guard", note: "Protects against loop-inconsistent states" },
        ],
        correct: "bpdu-guard",
        explain: "BPDU Guard is the edge-port defense — it err-disables the port the instant an unexpected BPDU appears.",
        wrongGuidance: "This is an access port with an unexpected BPDU — the feature that err-disables edge ports is BPDU Guard.",
      },
      {
        kind: "checkpoint",
        title: "The hijacker",
        prompt: "A downstream switch is sending superior BPDUs on a designated uplink. Which feature stops it from becoming root?",
        options: [
          { value: "root-guard", title: "Root Guard", note: "Rejects superior root claims on designated ports" },
          { value: "bpdu-guard", title: "BPDU Guard", note: "For edge ports expecting no BPDUs at all" },
          { value: "loop-guard", title: "Loop Guard", note: "Not about root claims" },
        ],
        correct: "root-guard",
        explain: "Root Guard protects the designated path: it blocks superior BPDUs so the root cannot be hijacked.",
        wrongGuidance: "The port is a designated uplink facing another switch — that is exactly where Root Guard belongs.",
      },
    ],
  },
  {
    id: "rescue-stp-mst",
    mission: "stp",
    phases: ["mst_concept"],
    isDefault: false,
    title: "Taming hundreds of VLANs",
    teaches: "MST maps many VLANs to a small set of spanning-tree instances.",
    tip: "The scale answer is MST: fewer instances, same loop protection.",
    steps: [
      {
        kind: "explain",
        title: "The many-instance problem",
        body: "PVST+ runs a separate spanning-tree instance per VLAN. With hundreds of VLANs, that is hundreds of instances chewing up control traffic. MST (Multiple Spanning Tree) maps many VLANs onto a small set of instances.",
      },
      {
        kind: "checkpoint",
        title: "The scale solution",
        prompt: "Hundreds of VLANs are creating too much spanning-tree control traffic. Which protocol groups VLANs into instances?",
        options: [
          { value: "mst", title: "MST", note: "Maps VLANs to fewer instances" },
          { value: "rstp", title: "RSTP", note: "Faster convergence, still one instance per VLAN" },
          { value: "pvst", title: "PVST+", note: "One instance per VLAN — the current problem" },
        ],
        correct: "mst",
        explain: "MST is the scale solution: it groups many VLANs into a small set of spanning-tree instances.",
        wrongGuidance: "You need FEWER instances. RSTP and PVST+ do not reduce the instance count — MST does.",
      },
      {
        kind: "explain",
        title: "Why it matters",
        body: "RSTP converges fast but still runs one instance per VLAN. MST gives you both speed and scale — which is why the campus picks it.",
      },
    ],
  },

  // ─── Bundled Bottleneck (EtherChannel) ─────────────────────────────────────
  {
    id: "rescue-ec-read",
    mission: "ec",
    phases: ["evidence"],
    isDefault: false,
    title: "Reading the bundle",
    teaches: "In show etherchannel summary, a (P) flag means bundled; a port with no flag never joined.",
    tip: "Look at the Ports column: Gi0/1(P) is in the bundle, Gi0/2 with no flag is not.",
    steps: [
      {
        kind: "explain",
        title: "The summary output",
        body: "show etherchannel summary lists each Port-Channel and its member ports. Each bundled port carries a (P) flag. A port with no flag at all is not part of the bundle — that is the evidence of a missing link.",
      },
      {
        kind: "checkpoint",
        title: "Read the flags",
        prompt: "The output shows Port-Channel 1 with Gi0/1(P) and Gi0/2 (no flag). What does that tell you?",
        options: [
          { value: "missing-link", title: "Only Gi0/1 joined Po1", note: "Gi0/2 never negotiated into the bundle" },
          { value: "healthy-bundle", title: "Both links are bundled", note: "Gi0/2 has no (P) flag" },
          { value: "no-lacp", title: "LACP is unsupported", note: "Nothing in the output says unsupported" },
        ],
        correct: "missing-link",
        explain: "A missing (P) flag means the link never joined the bundle — only Gi0/1 is bundled.",
        wrongGuidance: "Count the (P) flags. Gi0/2 shows none, so it never joined — that is a missing link.",
      },
    ],
  },
  {
    id: "rescue-ec-fix",
    mission: "ec",
    phases: ["cause", "config"],
    isDefault: true,
    title: "LACP modes: who starts?",
    teaches: "LACP active starts negotiating; passive waits. Passive + passive = nothing ever happens.",
    tip: "Flip one side to active: channel-group 1 mode active on SW1's Gi0/2.",
    steps: [
      {
        kind: "explain",
        title: "The handshake",
        body: "LACP needs one side to start talking. Active ports send LACP PDUs and listen; passive ports only listen. If BOTH ends are passive, neither side ever initiates — the bundle can never form.",
      },
      {
        kind: "checkpoint",
        title: "Why it is stuck",
        prompt: "SW1 Gi0/2 and SW2 Gi0/2 are both channel-group 1 mode passive. Why doesn't the link bundle?",
        options: [
          { value: "passive-passive", title: "Passive on both ends", note: "Nobody starts the negotiation" },
          { value: "group-mismatch", title: "Channel-group numbers differ", note: "Both are group 1 here" },
          { value: "access-mode", title: "Ports must be access mode", note: "Trunking is not the blocker" },
        ],
        correct: "passive-passive",
        explain: "With LACP passive on both ends, neither side sends the PDUs that start the bundle.",
        wrongGuidance: "Compare the modes, not the group numbers: both ends are passive, so nobody initiates.",
      },
      {
        kind: "cli",
        device: "SW1",
        prompt: "SW1(config-if)#",
        title: "Start the negotiation",
        command: "channel-group 1 mode active",
        expectedOutput: "LACP negotiation started — the passive neighbor will now respond.",
        wrongHint: "On SW1's Gi0/2 in config mode: channel-group 1 mode active",
        explain: "Active starts the handshake that the passive neighbor listens for, so Gi0/2 joins Po1.",
      },
    ],
  },
  {
    id: "rescue-ec-verify",
    mission: "ec",
    phases: ["verify"],
    isDefault: false,
    title: "Proving the bundle",
    teaches: "show etherchannel summary shows both members under Po1.",
    tip: "Verify with show etherchannel summary: you want Gi0/1(P) and Gi0/2(P) under Port-Channel 1 (SU).",
    steps: [
      {
        kind: "explain",
        title: "The proof",
        body: "show etherchannel summary is the canonical verification. Two ports with (P) flags under Port-Channel 1 (SU) prove both links are bundled.",
      },
      {
        kind: "checkpoint",
        title: "Pick the proof",
        prompt: "After the fix, which command proves both links are members of Port-Channel 1?",
        options: [
          { value: "summary", title: "show etherchannel summary", note: "Lists the (P) members of Po1" },
          { value: "vlan-brief", title: "show vlan brief", note: "Shows VLAN memberships, not bundles" },
          { value: "ip-brief", title: "show ip interface brief", note: "Interface status only" },
        ],
        correct: "summary",
        explain: "Only show etherchannel summary shows channel membership — the (P) flags under Po1.",
        wrongGuidance: "You need channel membership. show vlan brief and show ip interface brief show VLANs and interface status, not the bundle.",
      },
    ],
  },

  // ─── Area Zero Hero (OSPF) ─────────────────────────────────────────────────
  {
    id: "rescue-ospf-adjacency",
    mission: "ospf",
    phases: ["evidence"],
    isDefault: false,
    title: "Neighbor states",
    teaches: "OSPF neighbors climb to FULL; stuck in EXSTART means they see each other but cannot agree.",
    tip: "EXSTART is not FULL. Read the neighbor state before choosing an answer.",
    steps: [
      {
        kind: "explain",
        title: "The state ladder",
        body: "OSPF neighbors move Down → Init → Two-Way → ExStart → Exchange → Loading → FULL. FULL means the adjacency is up and routes flow. Getting stuck at an earlier state (like EXSTART) means the routers see each other but cannot agree — a mismatch somewhere.",
      },
      {
        kind: "checkpoint",
        title: "Read the state",
        prompt: "R1's show ip ospf neighbor shows R2 stuck in EXSTART, and the log says 'mismatch area 1, should be 0'. What does this tell you?",
        options: [
          { value: "stuck", title: "The adjacency is failing", note: "EXSTART is not FULL" },
          { value: "converged", title: "Both routers are converged", note: "FULL is the converged state" },
          { value: "down", title: "OSPF is not running", note: "A neighbor entry proves it runs" },
        ],
        correct: "stuck",
        explain: "EXSTART (not FULL) plus the area-mismatch log means the adjacency is stuck.",
        wrongGuidance: "EXSTART is far below FULL — the routers see each other but cannot finish the adjacency.",
      },
    ],
  },
  {
    id: "rescue-ospf-area",
    mission: "ospf",
    phases: ["cause", "config"],
    isDefault: true,
    title: "Areas must agree",
    teaches: "Both ends of an OSPF segment must be in the same area; area 0 is the backbone.",
    tip: "Put R2's link in area 0: network 10.0.2.0 0.0.0.255 area 0.",
    steps: [
      {
        kind: "explain",
        title: "One segment, one area",
        body: "Every OSPF link belongs to exactly one area. Two routers on the same segment MUST agree on that area or the adjacency never forms. Area 0 is the backbone every other area connects to.",
      },
      {
        kind: "checkpoint",
        title: "Name the fault",
        prompt: "R1's Gi0/1 is in area 0; R2's Gi0/1 is in area 1. What is wrong?",
        options: [
          { value: "area-mismatch", title: "Shared segment, two areas", note: "Both ends must agree" },
          { value: "router-id", title: "Router IDs conflict", note: "Router IDs are unique here" },
          { value: "process-id", title: "Process IDs differ", note: "Process IDs are local and never need to match" },
        ],
        correct: "area-mismatch",
        explain: "Both ends of the segment must share one area — here R2's link sits in area 1.",
        wrongGuidance: "Process IDs never need to match and router IDs are unique. The fault is the area — R2's link is in the wrong one.",
      },
      {
        kind: "cli",
        device: "R2",
        prompt: "R2(config-router)#",
        title: "Fix the area",
        command: "network 10.0.2.0 0.0.0.255 area 0",
        expectedOutput: "Network statement applied — 10.0.2.0/24 now belongs to area 0.",
        wrongHint: "Under router ospf 1 on R2: network 10.0.2.0 0.0.0.255 area 0",
        explain: "R2's link now matches R1's area 0, so the adjacency can form.",
      },
    ],
  },
  {
    id: "rescue-ospf-verify",
    mission: "ospf",
    phases: ["verify"],
    isDefault: false,
    title: "FULL means fixed",
    teaches: "A neighbor state of FULL/ - is the proof the adjacency is up.",
    tip: "Verify with show ip ospf neighbor — you want FULL/ - for R2.",
    steps: [
      {
        kind: "explain",
        title: "The green light",
        body: "When two OSPF neighbors reach FULL, they exchange routes. A neighbor entry showing FULL/ - is the standard proof that an adjacency is established.",
      },
      {
        kind: "checkpoint",
        title: "Pick the proof",
        prompt: "Which output proves R2 now reaches FULL and learns the core routes?",
        options: [
          { value: "full", title: "show ip ospf neighbor → FULL/ -", note: "The adjacency is established" },
          { value: "exstart", title: "Still EXSTART", note: "The adjacency is still broken" },
          { value: "cdp", title: "show cdp neighbors", note: "Shows devices, not adjacency" },
        ],
        correct: "full",
        explain: "A FULL/ - state for R2 proves the adjacency is up and routes flow.",
        wrongGuidance: "EXSTART means stuck; CDP shows attached devices. You want the FULL state.",
      },
    ],
  },
  {
    id: "rescue-ospf-summary",
    mission: "ospf",
    phases: ["summarize"],
    isDefault: false,
    title: "Summaries on the ABR",
    teaches: "area X range on the ABR collapses many subnets into one summary for other areas.",
    tip: "On R2: area 1 range 172.16.0.0 255.255.252.0.",
    steps: [
      {
        kind: "explain",
        title: "Flooding control",
        body: "An ABR sits between areas. Without summarization, every subnet from area 1 floods into area 0. The command area X range <network> <mask> on the ABR advertises ONE summary instead.",
      },
      {
        kind: "checkpoint",
        title: "Pick the summary",
        prompt: "Which command on R2 (the ABR) collapses 24 separate /30 routes into one 172.16.0.0/22 for area 0?",
        options: [
          { value: "area-range", title: "area 1 range 172.16.0.0 255.255.252.0", note: "ABR inter-area summarization" },
          { value: "summary-address", title: "summary-address 172.16.0.0 255.255.252.0", note: "For redistributed external routes (ASBR)" },
          { value: "network-statement", title: "network 172.16.0.0 0.0.3.255 area 0", note: "Not a summary — it claims the range in area 0" },
        ],
        correct: "area-range",
        explain: "area X range is the ABR's inter-area summary tool — one /22 instead of 24 /30s.",
        wrongGuidance: "summary-address is for redistributed routes on an ASBR; a network statement is not a summary. The ABR uses area X range.",
      },
      {
        kind: "cli",
        device: "R2",
        prompt: "R2(config-router)#",
        title: "Apply the summary",
        command: "area 1 range 172.16.0.0 255.255.252.0",
        expectedOutput: "Route summary for area 1 installed — 24 /30 routes collapse into one /22.",
        wrongHint: "Under router ospf 1 on R2: area 1 range 172.16.0.0 255.255.252.0",
        explain: "The ABR now advertises one summary prefix into area 0.",
      },
    ],
  },
  {
    id: "rescue-ospf-filter",
    mission: "ospf",
    phases: ["filter"],
    isDefault: false,
    title: "Filter at the ABR edge",
    teaches: "area X filter-list prefix ... out blocks Type-3 LSAs as they leave an area.",
    tip: "On R2: area 1 filter-list prefix LabDeny out.",
    steps: [
      {
        kind: "explain",
        title: "Where to filter",
        body: "Type-3 LSAs are created at the ABR as routes leave one area for another. To stop a prefix from ever entering area 0, filter as it leaves area 1: area 1 filter-list prefix <name> out.",
      },
      {
        kind: "checkpoint",
        title: "Pick the filter",
        prompt: "The lab prefix 192.168.50.0/24 must never cross into area 0. Which filter on R2 (the ABR) stops the Type-3 LSA as it leaves area 1?",
        options: [
          { value: "area-filter-out", title: "area 1 filter-list prefix LabDeny out", note: "Drops the LSA at the ABR edge" },
          { value: "distribute-out", title: "distribute-list prefix LabDeny out", note: "Only filters redistributed routes" },
          { value: "distribute-in", title: "distribute-list prefix LabDeny in", note: "Hides it from R1's table, too late" },
        ],
        correct: "area-filter-out",
        explain: "The ABR's area filter-list, applied out, blocks the Type-3 LSA before it enters area 0.",
        wrongGuidance: "distribute-list out touches only redistributed routes; filtering in is too late. The ABR needs area X filter-list ... out.",
      },
    ],
  },

  // ─── The Edge Has Opinions ─────────────────────────────────────────────────
  {
    id: "rescue-edge-igp",
    mission: "edge",
    phases: ["igp", "convergence"],
    isDefault: true,
    title: "EIGRP vs OSPF in one screen",
    teaches: "EIGRP: hybrid, composite metric, DUAL backup paths. OSPF: link-state, cost metric, SPF recalculation.",
    tip: "EIGRP = feasible-successor failover; OSPF = SPF recalculation. Keep the roles straight.",
    steps: [
      {
        kind: "explain",
        title: "Two engines, two styles",
        body: "EIGRP is Cisco's hybrid: it uses a composite metric (bandwidth, delay, load, reliability) and pre-computes backup paths called feasible successors. OSPF is link-state: every router builds a topology map and runs SPF, with cost as its metric.",
      },
      {
        kind: "checkpoint",
        title: "Pick the correct comparison",
        prompt: "Which comparison of EIGRP and OSPF is correct?",
        options: [
          { value: "hybrid-vs-linkstate", title: "EIGRP hybrid, OSPF link-state", note: "Composite metric vs cost" },
          { value: "classes-reversed", title: "EIGRP link-state, OSPF distance-vector", note: "Roles are swapped — wrong" },
          { value: "both-linkstate", title: "Both are link-state", note: "EIGRP is not link-state" },
        ],
        correct: "hybrid-vs-linkstate",
        explain: "EIGRP is the hybrid with a composite metric; OSPF is link-state with a cost metric.",
        wrongGuidance: "Keep the roles straight: EIGRP is a hybrid distance-vector protocol; OSPF is the link-state SPF protocol.",
      },
      {
        kind: "checkpoint",
        title: "Convergence",
        prompt: "Which best describes how each protocol converges after a topology change?",
        options: [
          { value: "fs-vs-spf", title: "EIGRP feasible successor vs OSPF SPF", note: "Instant failover vs recalculation" },
          { value: "holddown", title: "OSPF uses holddown timers", note: "A classic distance-vector tool" },
          { value: "lsa-flood", title: "EIGRP floods LSAs", note: "OSPF floods; EIGRP sends partial updates" },
        ],
        correct: "fs-vs-spf",
        explain: "EIGRP falls to a feasible successor almost instantly; OSPF recalculates via SPF.",
        wrongGuidance: "Holddown is distance-vector, and LSA flooding is OSPF. EIGRP's trick is the feasible successor.",
      },
    ],
  },
  {
    id: "rescue-edge-bgp",
    mission: "edge",
    phases: ["bgp-state", "bgp-fix"],
    isDefault: false,
    title: "eBGP across two hops",
    teaches: "eBGP assumes directly connected peers (TTL 1); two-hop peers need ebgp-multihop.",
    tip: "Under router bgp 65100 on R-EDGE: neighbor 203.0.113.2 ebgp-multihop 2, then verify with show ip bgp summary.",
    steps: [
      {
        kind: "explain",
        title: "Active is not a session",
        body: "In show ip bgp summary, Active means BGP is still trying to open the session — it has never become Established. eBGP assumes peers are directly connected (TTL 1), but these peers are two hops apart with a transit router between them.",
      },
      {
        kind: "checkpoint",
        title: "Name the blocker",
        prompt: "R-EDGE peers eBGP with ISP-R (AS 65001), two hops apart. The session stays Active. What is missing?",
        options: [
          { value: "multihop", title: "ebgp-multihop for the two-hop peer", note: "Raises the TTL so the session can cross the transit router" },
          { value: "as-mismatch", title: "The AS numbers must match", note: "eBGP requires different ASes — they already are" },
          { value: "md5", title: "A BGP password (MD5)", note: "Not configured and not the blocker" },
        ],
        correct: "multihop",
        explain: "Two-hop eBGP peers need the TTL raised with ebgp-multihop — the session can then establish.",
        wrongGuidance: "The ASes are already different (65100 vs 65001), and no password was configured. The missing piece is the multihop TTL.",
      },
      {
        kind: "cli",
        device: "R-EDGE",
        prompt: "R-EDGE(config-router)#",
        title: "Raise the TTL",
        command: "neighbor 203.0.113.2 ebgp-multihop 2",
        expectedOutput: "eBGP multihop enabled for neighbor 203.0.113.2 (max hops 2).",
        wrongHint: "Under router bgp 65100 on R-EDGE: neighbor 203.0.113.2 ebgp-multihop 2",
        explain: "The TTL is raised to 2, so the eBGP session can cross the transit router and establish.",
      },
    ],
  },
  // ─── Gateway at Dawn (HSRP / VRRP) ────────────────────────────────────────
  {
    id: "rescue-gateway-hsrp",
    mission: "gateway",
    phases: ["hsrp-config", "failover"],
    isDefault: true,
    title: "HSRP in one screen",
    teaches: "Virtual IP + priority + preempt on both gateways, and what the failover actually proves.",
    tip: "Back in the mission: on GW1's Gi0/1 add standby 1 ip 10.30.0.1, standby 1 priority 110, standby 1 preempt, then verify with show standby.",
    steps: [
      {
        kind: "explain",
        title: "One address, two routers",
        body: "HSRP makes two routers look like ONE gateway. Both hold the same virtual IP (10.30.0.1) and virtual MAC (0000.0c07.ac01). The Active router answers ARP for that address and forwards traffic; the Standby watches. If the Active dies, the Standby becomes Active and keeps the same address — hosts never notice.",
      },
      {
        kind: "checkpoint",
        title: "Who is Active?",
        prompt: "GW1 has priority 110 and preempt enabled; GW2 uses the default priority 100. Both share the virtual IP. Which router is Active?",
        options: [
          { value: "gw1", title: "GW1 — higher priority", note: "110 > 100, and preempt lets it reclaim the role" },
          { value: "gw2", title: "GW2 — lower priority", note: "Lower priority loses the election" },
          { value: "tie", title: "They alternate", note: "HSRP elects one Active, not a rotation" },
        ],
        correct: "gw1",
        explain: "The highest priority wins, and preempt lets GW1 take the role back whenever it returns.",
        wrongGuidance: "Compare priorities: 110 beats 100. Preempt means the higher-priority router reclaims Active when it comes back.",
      },
      {
        kind: "cli",
        device: "GW1",
        prompt: "GW1(config-if)#",
        title: "Set the virtual IP",
        command: "standby 1 ip 10.30.0.1",
        expectedOutput: "HSRP group 1 virtual IP set to 10.30.0.1.",
        wrongHint: "You are on GW1's Gi0/1 in config mode — type: standby 1 ip 10.30.0.1",
        explain: "The virtual IP is the address hosts point at — both gateways share it for group 1.",
      },
    ],
  },
  {
    id: "rescue-gateway-fhrp",
    mission: "gateway",
    phases: ["design", "ha", "vrrp"],
    isDefault: false,
    title: "FHRP: the what and the why",
    teaches: "Why a gateway needs redundancy (design + HA) and how HSRP differs from VRRP.",
    tip: "FHRP = virtual gateway shared by a pair. HSRP uses virtual MAC 0000.0c07.acXX; VRRP uses the active router's real MAC.",
    steps: [
      {
        kind: "explain",
        title: "Why a pair?",
        body: "End hosts configure ONE default gateway. If that device dies, they are stranded. A first-hop redundancy protocol (FHRP) shares a virtual IP across two gateways: HSRP, VRRP, and GLBP all do this. The pair sits at the distribution layer of a two-tier design, so the redundant first hop is designed in from the start.",
      },
      {
        kind: "checkpoint",
        title: "The redundant first hop",
        prompt: "Which mechanism gives end hosts a single virtual gateway that survives a switch failure?",
        options: [
          { value: "fhrp", title: "An FHRP (HSRP / VRRP / GLBP)", note: "A virtual IP shared by two gateways" },
          { value: "stp", title: "STP root election", note: "Loop prevention, not gateway redundancy" },
          { value: "ecmp", title: "Equal-cost multipath", note: "For routers, not host default gateways" },
        ],
        correct: "fhrp",
        explain: "FHRPs present one virtual gateway to hosts while two routers cover for each other.",
        wrongGuidance: "STP prevents loops and ECMP is a routing-table tool. Hosts need a redundant first hop — that is an FHRP.",
      },
      {
        kind: "checkpoint",
        title: "HSRP vs VRRP",
        prompt: "Which statement correctly contrasts HSRP and VRRP?",
        options: [
          { value: "virtual-mac", title: "HSRP virtual MAC vs VRRP real MAC", note: "0000.0c07.acXX vs the active router's own MAC" },
          { value: "same-mac", title: "Both use one shared virtual MAC", note: "Only HSRP has the well-known virtual MAC" },
          { value: "vrrp-no-preempt", title: "VRRP disables preemption by default", note: "VRRP preempts by default — HSRP needs the command" },
        ],
        correct: "virtual-mac",
        explain: "HSRP answers with virtual MAC 0000.0c07.acXX; VRRP's master uses its own real MAC, so neighbor ARP caches churn on failover.",
        wrongGuidance: "Compare the MACs: HSRP owns a well-known virtual MAC; VRRP uses the active router's real one.",
      },
    ],
  },

  // ─── Edge Services (QoS / NTP / NAT-PAT / multicast) ──────────────────────
  {
    id: "rescue-edge-services-qos",
    mission: "edge-services",
    phases: ["qos"],
    isDefault: false,
    title: "Reading an MQC policy",
    teaches: "QoS in three pieces: class-map classifies, policy-map acts, service-policy attaches.",
    tip: "priority = strict LLQ queue; bandwidth = guaranteed share; a class-map only matches, it never marks.",
    steps: [
      {
        kind: "explain",
        title: "Classify, act, attach",
        body: "Modular QoS (MQC) has three pieces. A class-map classifies traffic by matching something — here, DSCP EF. A policy-map acts on each class: priority gives strict-priority (LLQ) queueing, bandwidth guarantees a share. A service-policy attaches the policy to an interface in the right direction.",
      },
      {
        kind: "checkpoint",
        title: "Read the policy",
        prompt: "class VOICE matches dscp ef and the policy-map gives it priority 1000. What does that actually do?",
        options: [
          { value: "voice-ef", title: "Voice gets strict priority", note: "priority 1000 is LLQ, the strict queue" },
          { value: "policy-marks", title: "The policy marks voice as EF", note: "Marking would need set dscp — not present" },
          { value: "policy-shapes", title: "The policy shapes to 20 Mbps", note: "Shaping needs shape average, not bandwidth" },
        ],
        correct: "voice-ef",
        explain: "priority is strict-priority queueing — voice (EF) always goes first. Nothing here marks or shapes.",
        wrongGuidance: "Compare the commands: priority is queueing, set dscp is marking, shape average is shaping — only priority appears.",
      },
      {
        kind: "explain",
        title: "Remember for the mission",
        body: "class-map = classification (match), policy-map = action (priority/bandwidth/police/shape/set), service-policy = attachment point. Match the command to the job.",
      },
    ],
  },
  {
    id: "rescue-edge-services-ntp",
    mission: "edge-services",
    phases: ["ntp"],
    isDefault: false,
    title: "NTP vs PTP in one screen",
    teaches: "NTP syncs over UDP/123 and slews; ntp source pins the address; PTP is the hardware-timestamped alternative.",
    tip: "ntp source gives stable addressing; NTP never steps the clock on a normal sync; PTP uses boundary/transparent clocks.",
    steps: [
      {
        kind: "explain",
        title: "One clock, many routers",
        body: "NTP keeps network devices in sync over UDP/123 and corrects the clock gradually (it slews, it does not step). ntp source pins which address the router sends NTP packets from, so sync survives interface flapping. Authentication needs all three pieces: ntp authenticate, an authentication-key, and that key listed as trusted.",
      },
      {
        kind: "checkpoint",
        title: "Read the clock config",
        prompt: "The config has ntp source Loopback0, ntp authenticate, an authentication-key, and a trusted-key. Which statement about it is correct?",
        options: [
          { value: "source-lo", title: "ntp source pins the source address", note: "Stable addressing survives WAN flaps" },
          { value: "steps-clock", title: "The clock steps immediately", note: "NTP slews gradually" },
          { value: "ptp-config", title: "This is a PTP boundary clock", note: "PTP uses boundary/transparent clocks" },
        ],
        correct: "source-lo",
        explain: "ntp source Loopback0 makes NTP replies originate from a stable address — the correct read of the config.",
        wrongGuidance: "NTP slews, it does not step; and this is an NTP config — PTP would show boundary or transparent clocks.",
      },
      {
        kind: "explain",
        title: "When PTP wins",
        body: "PTP (IEEE 1588) uses hardware timestamps and boundary/transparent clocks for sub-microsecond accuracy — the choice for trading floors and data centers, overkill for a branch.",
      },
    ],
  },
  {
    id: "rescue-edge-services-nat",
    mission: "edge-services",
    phases: ["nat-config", "nat-drill"],
    isDefault: true,
    title: "NAT/PAT in one screen",
    teaches: "NAT translates private to public; PAT overloads one public address with many ports.",
    tip: "Back in the mission: mark gi0/0 inside and gi0/1 outside, permit the LAN with an ACL, then ip nat inside source list 1 interface gi0/1 overload.",
    steps: [
      {
        kind: "explain",
        title: "One address, many hosts",
        body: "NAT rewrites the source address as traffic leaves the private network. PAT (overload) goes further: many LAN hosts share ONE public address, each flow identified by its port. Without the overload keyword, each concurrent flow would need its own public IP.",
      },
      {
        kind: "checkpoint",
        title: "The four pieces",
        prompt: "Which set is required for PAT to translate LAN traffic out of one WAN address?",
        options: [
          { value: "full-set", title: "Inside + outside + ACL + overload", note: "Mark both interfaces, permit the LAN, share the WAN address" },
          { value: "acl-only", title: "Just an ACL matching the LAN", note: "Without inside/outside marks, NAT has nowhere to apply" },
          { value: "static", title: "One static mapping per host", note: "Defeats the whole point of PAT's shared address" },
        ],
        correct: "full-set",
        explain: "PAT needs the inside/outside interface marks, an ACL defining interesting traffic, and the overload rule sharing the WAN address.",
        wrongGuidance: "An ACL alone is just classification; static mappings are the opposite of overload. You need all four pieces.",
      },
      {
        kind: "cli",
        device: "R-EDGE",
        prompt: "R-EDGE(config)#",
        title: "Enable PAT",
        command: "ip nat inside source list 1 interface gi0/1 overload",
        expectedOutput: "PAT enabled — LAN flows will share 203.0.113.5 using overloaded ports.",
        wrongHint: "In global config on R-EDGE: ip nat inside source list 1 interface gi0/1 overload",
        explain: "The overload rule tells NAT to share the WAN interface address across many LAN flows.",
      },
    ],
  },
  {
    id: "rescue-edge-services-multicast",
    mission: "edge-services",
    phases: ["multicast"],
    isDefault: false,
    title: "RPF, PIM, IGMP — and the family",
    teaches: "RPF is the loop guard, PIM-SM builds shared trees with joins, IGMPv3 adds source-specific joins; SSM serves one-to-many, bidir PIM handles many-to-many via a shared tree, and MSDP peers RPs between PIM-SM domains.",
    tip: "Loop safety = RPF. Tree building = PIM. Host membership = IGMP. IGMPv3 lets hosts join specific sources. SSM = one-to-many (S,G); bidir = one shared tree; MSDP = RPs peering across domains.",
    steps: [
      {
        kind: "explain",
        title: "How multicast stays loop-free",
        body: "Multicast has no routing-table loop prevention, so routers run an RPF check: a packet is forwarded only if it arrived on the interface that leads back toward the source. PIM builds the delivery trees — sparse mode with explicit joins, dense mode with flooding. Hosts signal membership with IGMP.",
      },
      {
        kind: "checkpoint",
        title: "Pick the loop guard",
        prompt: "Which statement about multicast is correct?",
        options: [
          { value: "rpf-check", title: "RPF checks the source interface", note: "Forward only if the packet arrives on the path to the source" },
          { value: "spm-flood", title: "PIM sparse mode floods everywhere", note: "Sparse mode builds shared trees with explicit joins" },
          { value: "igmpv3-any", title: "IGMPv3 joins are always any-source", note: "IGMPv3 adds source-specific (S,G) joins" },
        ],
        correct: "rpf-check",
        explain: "The RPF check is multicast's loop guard — a packet is dropped unless it arrives on the interface toward the source.",
        wrongGuidance: "Sparse mode is explicit-join, not flooding; and IGMPv3's whole point is source-specific joins. RPF is the loop guard.",
      },
      {
        kind: "checkpoint",
        title: "Name the domain bridge",
        prompt: "Two PIM-SM domains each run their own RP. Which protocol lets them exchange source information so one domain's sources are reachable in the other?",
        options: [
          { value: "msdp-peers", title: "MSDP — RPs peer across domains", note: "Source info flows over TCP 639 between RPs" },
          { value: "bidir-flood", title: "Bidir PIM floods to every receiver", note: "Bidir uses one shared tree through the RP — it never floods" },
          { value: "ssm-many", title: "SSM for many-to-many groups", note: "SSM is one-to-many, source-specific (S,G) trees" },
        ],
        correct: "msdp-peers",
        explain: "MSDP peers each domain's RP with the others (TCP 639), so source information crosses PIM-SM domain boundaries.",
        wrongGuidance: "Bidir PIM is a single shared tree through the RP for many-to-many, and SSM is source-specific one-to-many — neither bridges domains. That is MSDP's job.",
      },
      {
        kind: "explain",
        title: "Keep the family straight",
        body: "RPF = loop prevention on every multicast router. PIM = building the tree between routers (sparse mode joins on demand). IGMP = hosts asking for groups (v2 any-source, v3 source-specific). Then the family: SSM builds source-specific (S,G) trees for one-to-many delivery; bidir PIM serves dense many-to-many groups with a single shared tree through the RP; MSDP peers RPs so separate PIM-SM domains can share sources.",
      },
    ],
  },

  // ─── Tunnel Vision (VRF / GRE / IPsec) ─────────────────────────────────────
  {
    id: "rescue-overlay-vrf",
    mission: "tunnel-vision",
    phases: ["vrf"],
    isDefault: false,
    title: "VRF in one screen",
    teaches: "A VRF is its own routing table — and vrf forwarding on an interface strips its IP address.",
    tip: "Back in the mission: vrf definition GUEST → rd 65000:20 → interface gi0/1 → vrf forwarding GUEST (strips the IP!) → re-add ip address 192.168.20.1 255.255.255.0.",
    steps: [
      {
        kind: "explain",
        title: "Tables within the router",
        body: "A VRF (Virtual Routing and Forwarding) gives a router multiple independent routing tables. Each VRF has a route distinguisher (rd) that keeps its routes unique, and interfaces are bound to it with vrf forwarding. The classic gotcha: applying vrf forwarding to an interface with an IP address strips that address — you must re-add it inside the VRF.",
      },
      {
        kind: "checkpoint",
        title: "Pick the isolation tool",
        prompt: "Guest traffic must stop sharing the corporate routing table. Which configuration gives the guests their own table?",
        options: [
          { value: "vrf-definition", title: "vrf definition GUEST + rd", note: "A separate routing table with its own RD" },
          { value: "access-list", title: "An extended access list", note: "Filters traffic — it does not isolate routing tables" },
          { value: "vlan", title: "A separate VLAN number", note: "Layer 2 segmentation, not a separate routing table" },
        ],
        correct: "vrf-definition",
        explain: "VRFs create isolated routing tables; the rd keeps each VRF's routes unique.",
        wrongGuidance: "ACLs filter and VLANs segment Layer 2 — neither gives a router a second routing table. That is what a VRF does.",
      },
      {
        kind: "cli",
        device: "R-BR",
        prompt: "R-BR(config)#",
        title: "Create the guest VRF",
        command: "vrf definition GUEST",
        expectedOutput: "VRF GUEST created — enter its config to add the route distinguisher.",
        wrongHint: "In global config on R-BR: vrf definition GUEST",
        explain: "vrf definition opens the VRF's configuration mode, where rd assigns its unique route distinguisher.",
      },
    ],
  },
  {
    id: "rescue-overlay-gre",
    mission: "tunnel-vision",
    phases: ["gre"],
    isDefault: false,
    title: "GRE tunnel anatomy",
    teaches: "A GRE tunnel needs an IP, a source, a destination, and the GRE mode — then the overlay can cross the underlay.",
    tip: "interface tunnel 0 → ip address → tunnel source gi0/0 → tunnel destination 203.0.113.1 → tunnel mode gre ip.",
    steps: [
      {
        kind: "explain",
        title: "A tunnel is a virtual interface",
        body: "GRE (Generic Routing Encapsulation) wraps an entire IP packet inside another IP packet, so the overlay can cross a network that knows nothing about it — and it can carry multicast and routing protocols too. The tunnel interface needs its own IP on the overlay subnet, a tunnel source (the local WAN interface or address), a tunnel destination (the far WAN address), and tunnel mode gre ip.",
      },
      {
        kind: "checkpoint",
        title: "Build the tunnel",
        prompt: "Which set of commands creates the GRE tunnel from R-BR to HQ (203.0.113.1)?",
        options: [
          { value: "gre-set", title: "interface tunnel 0 + tunnel source/destination", note: "Plus an IP and tunnel mode gre ip" },
          { value: "crypto-set", title: "crypto map + transform set", note: "That encrypts — the tunnel itself is built first" },
          { value: "vrf-set", title: "vrf definition + rd", note: "That creates routing tables, not the tunnel" },
        ],
        correct: "gre-set",
        explain: "The tunnel interface with tunnel source and destination is what carries the overlay across the internet.",
        wrongGuidance: "Crypto maps encrypt and VRFs isolate — the virtual interface that transports the overlay is the GRE tunnel.",
      },
    ],
  },
  {
    id: "rescue-overlay-ipsec",
    mission: "tunnel-vision",
    phases: ["ipsec", "cryptomap", "checkpoint"],
    isDefault: true,
    title: "IPsec in one screen",
    teaches: "IKE phase 1 builds the keying; the crypto map + ACL decide what gets encrypted — for GRE-over-IPsec that is the GRE flow itself.",
    tip: "For GRE-over-IPsec the ACL matches the GRE flow between the WAN endpoints (permit gre host 198.51.100.2 host 203.0.113.1), never the inner private subnets.",
    steps: [
      {
        kind: "explain",
        title: "Two phases, one decision",
        body: "IPsec IKE phase 1 (ISAKMP) negotiates the keying between peers — policy, pre-shared key, and a transform set. Phase 2, driven by a crypto map, decides WHAT gets encrypted: the map's ACL is the traffic of interest. With GRE-over-IPsec, the ACL must match the GRE packets themselves (protocol 47) between the WAN endpoints, because the inner private IPs ride inside the GRE payload.",
      },
      {
        kind: "checkpoint",
        title: "Read the local ident",
        prompt: "show crypto ipsec sa shows local ident (addr/mask/prot/port): (198.51.100.2/255.255.255.255/47/0). What does the 47 tell you?",
        options: [
          { value: "gre-protected", title: "The map protects GRE traffic", note: "Protocol 47 is GRE — the outer tunnel flow" },
          { value: "inner-subnets", title: "The map protects private subnets", note: "Inner IPs are not in the ident — they ride inside" },
          { value: "no-acl", title: "No ACL is matched at all", note: "PERMIT with flags={origin_is_acl} means an ACL drives it" },
        ],
        correct: "gre-protected",
        explain: "Protocol 47 in the ident means the crypto map is encrypting the GRE flow — exactly right for GRE-over-IPsec.",
        wrongGuidance: "The ident shows the OUTER protocol (47 = GRE). The inner private subnets are inside the encrypted GRE payload, invisible here.",
      },
      {
        kind: "cli",
        device: "R-BR",
        prompt: "R-BR(config)#",
        title: "Define the transform set",
        command: "crypto ipsec transform-set TS esp-aes 256 esp-sha-hmac",
        expectedOutput: "Transform set TS created: esp-aes 256 with esp-sha-hmac integrity.",
        wrongHint: "In global config on R-BR: crypto ipsec transform-set TS esp-aes 256 esp-sha-hmac",
        explain: "The transform set defines phase 2 protection — here AES-256 encryption with SHA-HMAC integrity (note the explicit 256).",
      },
    ],
  },

  // ─── The Fabric Express (hypervisors / VMs / vSwitch / VXLAN) ─────────────
  {
    id: "rescue-fabric-hypervisor",
    mission: "fabric-express",
    phases: ["hypervisor", "vm"],
    isDefault: true,
    title: "Hypervisors and the VM",
    teaches: "Type 1 hypervisors own the hardware; a VM's resources are virtual hardware backed by the host.",
    tip: "ESXi is bare-metal (Type 1). A vNIC is virtual — it plugs into a vSwitch, never a physical port.",
    steps: [
      {
        kind: "explain",
        title: "Two kinds of hypervisor",
        body: "A hypervisor creates and runs VMs. Type 1 (bare-metal) installs directly on the hardware and owns every resource — ESXi, KVM, Hyper-V. Type 2 runs as an application on top of a host OS — VirtualBox, VMware Workstation. ESXi is Type 1: there is no host OS beneath it.",
      },
      {
        kind: "checkpoint",
        title: "Classify the hypervisor",
        prompt: "ESXi is installed straight onto the server with nothing beneath it. What kind of hypervisor is that?",
        options: [
          { value: "type1", title: "Type 1 — bare-metal", note: "Owns the hardware directly" },
          { value: "type2", title: "Type 2 — hosted", note: "Runs as an app on a host OS" },
          { value: "hosted-os", title: "It needs a host OS", note: "That would make it Type 2 — ESXi has none" },
        ],
        correct: "type1",
        explain: "Bare-metal means no host OS — ESXi installs directly on the hardware, so it is Type 1.",
        wrongGuidance: "Type 2 hypervisors sit on a host OS. ESXi IS the operating system on the metal — that is Type 1.",
      },
      {
        kind: "checkpoint",
        title: "Read the VM",
        prompt: "A VM shows 4 vCPU, 8 GB, and a vmxnet3 vNIC connected to VM Network. Which read is correct?",
        options: [
          { value: "virtual-hardware", title: "All virtual hardware", note: "vCPU/vNIC backed by the host, scheduled by the hypervisor" },
          { value: "physical-nic", title: "The vNIC is a physical adapter", note: "A vNIC is virtual and plugs into a vSwitch" },
          { value: "physical-disk", title: "The disk is a physical drive", note: "A vmdk is a file on the datastore" },
        ],
        correct: "virtual-hardware",
        explain: "The hypervisor carves vCPU, memory, and vNICs out of the host's physical resources.",
        wrongGuidance: "vNICs are virtual NIC hardware connected to a vSwitch, and a vmdk is a disk file — not physical.",
      },
    ],
  },
  {
    id: "rescue-fabric-vswitch",
    mission: "fabric-express",
    phases: ["vswitch", "vswitch-check"],
    isDefault: false,
    title: "The vSwitch and its uplinks",
    teaches: "A vSwitch is a virtual switch inside the hypervisor; its uplinks are physical NICs that carry VM traffic out.",
    tip: "List the vSwitch and the uplinks. The answer: without a connected uplink, VMs can only talk to each other.",
    steps: [
      {
        kind: "explain",
        title: "The switch inside the host",
        body: "Every VM's vNIC plugs into a vSwitch — a virtual switch running inside the hypervisor. Port groups bundle VMs into VLANs. To reach the physical network, the vSwitch needs an uplink: a physical NIC bound to it. If no uplink is connected, VMs can talk to each other but never leave the host.",
      },
      {
        kind: "checkpoint",
        title: "The island vSwitch",
        prompt: "A vSwitch has two port groups and zero uplinks. What can its VMs reach?",
        options: [
          { value: "each-other", title: "Only each other", note: "Without an uplink, no frame reaches a physical NIC" },
          { value: "physical-lan", title: "The physical LAN", note: "That requires a connected uplink" },
          { value: "internet", title: "The internet directly", note: "The internet is reached via the physical network" },
        ],
        correct: "each-other",
        explain: "No uplink means the vSwitch is isolated: intra-host traffic works, everything else is cut off.",
        wrongGuidance: "To leave the host, VM frames must cross a physical NIC — that is exactly what an uplink provides.",
      },
      {
        kind: "cli",
        device: "HOST-1",
        prompt: "HOST-1#",
        title: "Inspect the uplinks",
        command: "esxcli network vswitch standard uplink list",
        expectedOutput: "Uplink     Adapter  Link    Speed   Duplex\nvmnic0     vmnic0   Up      10000   Full",
        wrongHint: "In privileged mode on HOST-1: esxcli network vswitch standard uplink list",
        explain: "vmnic0 is Up — that is the physical NIC carrying VM traffic to the network.",
      },
    ],
  },
  {
    id: "rescue-fabric-vxlan",
    mission: "fabric-express",
    phases: ["vxlan", "vxlan-check"],
    isDefault: false,
    title: "VXLAN and the VNI",
    teaches: "VXLAN wraps Layer 2 frames in UDP; a VNI is the 24-bit overlay segment ID, and the VTEP (nve1) encapsulates.",
    tip: "A VNI is the overlay's Layer 2 segment number — VLAN 10 maps to VNI 10010, deliberately distinct numbers.",
    steps: [
      {
        kind: "explain",
        title: "Layer 2 over the IP network",
        body: "VXLAN lets Layer 2 segments span an IP underlay: the VTEP wraps each frame in UDP (port 4789) with a 24-bit VNI marking the segment. Config maps each VLAN to a vn-segment: vlan 10 → VNI 10010. The VNI is the overlay segment ID — the VLAN's Layer 3-independent identity inside VXLAN.",
      },
      {
        kind: "checkpoint",
        title: "Name the VNI",
        prompt: "nve1 shows member vni 10010 tied to vlan 10. What does VNI 10010 identify?",
        options: [
          { value: "l2-segment", title: "A Layer 2 segment in the overlay", note: "The 24-bit VXLAN segment ID" },
          { value: "vlan-number", title: "The same as the VLAN number", note: "VLAN 10 → VNI 10010 — the numbers differ on purpose" },
          { value: "vrf", title: "A routing table (VRF)", note: "VRFs are Layer 3; VNIs mark Layer 2 segments" },
        ],
        correct: "l2-segment",
        explain: "A VNI is the VXLAN segment identifier — the overlay equivalent of a VLAN.",
        wrongGuidance: "The config deliberately maps VLAN 10 to a DIFFERENT number (10010), and VRFs are a routing concept — VNIs identify Layer 2 segments.",
      },
      {
        kind: "cli",
        device: "LEAF-1",
        prompt: "LEAF-1#",
        title: "Read the VTEP",
        command: "show running-config interface nve1",
        expectedOutput: "interface nve1\n  source-interface Loopback0\n  member vni 10010\n    ingress-replication",
        wrongHint: "In privileged EXEC on LEAF-1: show running-config interface nve1",
        explain: "nve1 is the VTEP — it encapsulates frames into VNI 10010 and replicates them to the peers.",
      },
    ],
  },

  // ─── The Campus Fabric (SD-Access / LISP / legacy interop) ─────────────────
  {
    id: "rescue-campus-roles",
    mission: "campus-fabric",
    phases: ["roles"],
    isDefault: true,
    title: "The three fabric roles",
    teaches: "Edge nodes connect hosts, the border node faces the outside, and the control plane node runs LISP's map-server/map-resolver with the EID-to-RLOC database.",
    tip: "The mapping database lives in the control plane node. Edges register their hosts; the border connects outward.",
    steps: [
      {
        kind: "explain",
        title: "Edge, border, control plane",
        body: "SD-Access splits the fabric into three node roles. Fabric edge nodes connect the wired endpoints: they register their hosts' EIDs with the control plane and encapsulate/decapsulate traffic. The fabric border node connects the fabric to external networks. The control plane node runs the LISP map-server and map-resolver — it holds the EID-to-RLOC database, the fabric's answer to 'where is this host?'.",
      },
      {
        kind: "checkpoint",
        title: "Name the mapping brain",
        prompt: "Which SD-Access node keeps the EID-to-RLOC mapping database for the whole fabric?",
        options: [
          { value: "control-plane", title: "The control plane node", note: "LISP map-server/map-resolver" },
          { value: "edge", title: "Every edge node", note: "Edges register their own hosts only" },
          { value: "border", title: "The border node", note: "The border faces external networks" },
        ],
        correct: "control-plane",
        explain: "The control plane node hosts LISP and keeps the fabric-wide EID-to-RLOC database.",
        wrongGuidance: "Edges register and forward for their own hosts, and the border faces outward — the central mapping database is the control plane node's job.",
      },
    ],
  },
  {
    id: "rescue-campus-lisp",
    mission: "campus-fabric",
    phases: ["lisp", "lisp-check"],
    isDefault: false,
    title: "LISP: EIDs and RLOCs",
    teaches: "In LISP, endpoints are EIDs and fabric switches are RLOCs; the map-cache resolves an EID prefix to the RLOC that can reach it.",
    tip: "Back in the mission: on CP-1 run show lisp session, show lisp map-cache, and show lisp site.",
    steps: [
      {
        kind: "explain",
        title: "The two namespaces",
        body: "LISP separates the endpoint identity from its location. An EID (Endpoint Identifier) is the host or subnet prefix — 10.10.10.0/24. An RLOC (Routing Locator) is the fabric switch that can reach it — 192.0.2.10. The map-cache binds EID to RLOC, so an edge node that needs to reach 10.10.10.0/24 knows to encapsulate toward 192.0.2.10.",
      },
      {
        kind: "checkpoint",
        title: "Read the map-cache",
        prompt: "The map-cache shows 10.10.10.0/24 resolved to locator 192.0.2.10. What is that entry?",
        options: [
          { value: "eid-rloc", title: "An EID prefix mapped to an RLOC", note: "The endpoint resolved to its tunnel endpoint" },
          { value: "route", title: "A routing-table entry", note: "The cache maps EIDs, it is not a RIB" },
          { value: "bgp", title: "A BGP path", note: "BGP routes the underlay; LISP maps EIDs" },
        ],
        correct: "eid-rloc",
        explain: "The entry is exactly the EID-to-RLOC binding — how LISP tells an edge where to encapsulate.",
        wrongGuidance: "The cache is LISP's mapping, not a routing table — and BGP is the underlay's routing protocol, not the mapping database.",
      },
      {
        kind: "cli",
        device: "CP-1",
        prompt: "CP-1#",
        title: "Read the bindings",
        command: "show lisp map-cache",
        expectedOutput: "10.10.10.0/24  3w2d  192.0.2.10  1/100  up",
        wrongHint: "In privileged EXEC on CP-1: show lisp map-cache",
        explain: "Each EID prefix resolves to the RLOC of the edge node that serves it.",
      },
    ],
  },
  {
    id: "rescue-campus-interop",
    mission: "campus-fabric",
    phases: ["interop"],
    isDefault: false,
    title: "Legacy meets the fabric",
    teaches: "Legacy hosts reach fabric hosts through the border node (which advertises fabric prefixes outward) and the fusion router (shared services + route leaking).",
    tip: "Legacy hosts never run LISP or VXLAN — the border node and fusion router do the translation.",
    steps: [
      {
        kind: "explain",
        title: "One fabric, two worlds",
        body: "A legacy (non-fabric) host cannot query LISP or encapsulate VXLAN. The fabric meets the old world at the border node: it advertises fabric prefixes outward with BGP/OSPF and ingests external routes. The fusion router sits alongside it, providing shared services (DHCP, DNS, firewalls) and inter-VRF route leaking. Traffic from the legacy host enters the fabric at the border and flows to the destination edge node — the EID resolution happens inside the fabric.",
      },
      {
        kind: "checkpoint",
        title: "Pick the bridge",
        prompt: "How does a legacy (non-fabric) host reach a host inside the SD-Access fabric?",
        options: [
          { value: "border-fusion", title: "Through the border node + fusion router", note: "The border translates fabric ↔ legacy routing" },
          { value: "vxlan", title: "The legacy host runs VXLAN itself", note: "VXLAN is fabric-internal encapsulation" },
          { value: "blocked", title: "It cannot", note: "The border exists exactly to bridge them" },
        ],
        correct: "border-fusion",
        explain: "The border node advertises fabric prefixes outward and ingests external routes; the fusion router adds shared services.",
        wrongGuidance: "Legacy hosts never run VXLAN (it is fabric-internal), and interop definitely happens — through the border and fusion router.",
      },
    ],
  },

  // ─── SD-WAN: The WAN Overlay (planes / OMP / data plane) ───────────────────
  {
    id: "rescue-sdwan-planes",
    mission: "sdwan",
    phases: ["planes", "omp"],
    isDefault: true,
    title: "SD-WAN planes and OMP",
    teaches: "vManage (now SD-WAN Manager) manages, vSmart is the control plane (OMP route reflection), vBond (now SD-WAN Validator) orchestrates, vEdge forwards. OMP carries prefix + TLOC + attributes.",
    tip: "Control plane = OMP between vSmart and the vEdges. Data plane = the vEdges forwarding over TLOCs.",
    steps: [
      {
        kind: "explain",
        title: "Four roles, one fabric",
        body: "Catalyst SD-WAN splits into planes. vManage (now branded SD-WAN Manager) is the management plane: the UI, APIs, and monitoring. vSmart is the control plane: it runs OMP (Overlay Management Protocol), reflects routes, and pushes policy. vBond (now the SD-WAN Validator) is the orchestration plane: it authenticates new devices and tells them where to find vManage and vSmart. The vEdge routers are the data plane: they actually forward packets, in GRE/IPsec tunnels over any transport. Cisco's current names are SD-WAN Manager and SD-WAN Validator, but the classic vManage/vBond names still appear across CLI output and older material."
      },
      {
        kind: "checkpoint",
        title: "Name the control plane",
        prompt: "Which statement about the Catalyst SD-WAN planes is correct?",
        options: [
          { value: "control-omp", title: "OMP is the control plane", note: "vSmart reflects routes to the vEdges" },
          { value: "data-vsmart", title: "vSmart forwards packets", note: "vEdges forward; vSmart reflects and polices" },
          { value: "mgmt-vbond", title: "vBond manages the fabric", note: "vBond orchestrates; vManage manages" },
        ],
        correct: "control-omp",
        explain: "OMP between vSmart and the vEdges is the control plane; vManage (management) and vBond (orchestration) play different roles.",
        wrongGuidance: "vSmart is a controller, not a forwarder, and vBond orchestrates onboarding — it is vManage that manages. OMP is the control plane.",
      },
      {
        kind: "checkpoint",
        title: "Read an OMP route",
        prompt: "show omp routes shows a prefix with STATUS C,I,R and a TLOC IP. What is an OMP route?",
        options: [
          { value: "omp-tloc-attr", title: "Prefix + TLOC + attributes", note: "The control-plane info a vEdge needs to forward" },
          { value: "full-table", title: "The full routing table", note: "OMP reflects prefixes — never the whole table" },
          { value: "transit", title: "User packets riding OMP", note: "OMP is signaling; data flows in IPsec/GRE tunnels" },
        ],
        correct: "omp-tloc-attr",
        explain: "An OMP route binds a prefix to the TLOC that can reach it, over a secure DTLS/TLS channel.",
        wrongGuidance: "OMP carries routes, not traffic, and not the full table — each vEdge installs the prefixes it needs, pointed at TLOCs.",
      },
    ],
  },
  {
    id: "rescue-sdwan-datapath",
    mission: "sdwan",
    phases: ["tlocs", "tlocs-check"],
    isDefault: false,
    title: "TLOCs, BFD, and the data plane",
    teaches: "A TLOC (system IP + color + encapsulation) is the tunnel endpoint the data plane forwards over; BFD watches TLOCs for fast failover.",
    tip: "Back in the mission: on the vEdge run show omp tlocs, show bfd sessions, and show control connections.",
    steps: [
      {
        kind: "explain",
        title: "The tunnel endpoints",
        body: "A TLOC is the interface-level identifier of a WAN transport — its system IP, color, and encapsulation (ipsec/gre). OMP routes point at TLOCs. BFD sessions run over each TLOC and watch it: when a path dies, BFD tells the vEdge and it fails over to the other transport, usually in under a second.",
      },
      {
        kind: "checkpoint",
        title: "What does the data plane use?",
        prompt: "After verifying the vEdge, which statement about the data plane is correct?",
        options: [
          { value: "tlocs-forward", title: "Forwarding happens over TLOCs", note: "Routes point at TLOCs; BFD watches them" },
          { value: "tlocs-routes", title: "TLOCs replace OMP routes", note: "Routes reference TLOCs — both stay" },
          { value: "bfd-omp", title: "BFD replaces OMP", note: "BFD monitors; OMP still builds routes" },
        ],
        correct: "tlocs-forward",
        explain: "OMP routes resolve to TLOCs, and the vEdge forwards data over those TLOC tunnels — BFD is the liveliness check.",
        wrongGuidance: "TLOCs are the forwarding targets, not a replacement for routes — and BFD only watches paths, it never replaces OMP.",
      },
      {
        kind: "cli",
        device: "vEdge",
        prompt: "vEdge#",
        title: "Read the TLOCs",
        command: "show omp tlocs",
        expectedOutput: "ipv4  10.1.0.5  gold  ipsec  ...  BFD STATUS: up",
        wrongHint: "In privileged EXEC on the vEdge: show omp tlocs",
        explain: "The TLOC table lists the tunnel endpoints — and each shows a BFD status of up.",
      },
    ],
  },
  {
    id: "rescue-sdwan-benefit",
    mission: "sdwan",
    phases: ["benefit"],
    isDefault: false,
    title: "The SD-WAN tradeoff",
    teaches: "Benefits: transport independence, centralized policy, app-aware paths. Limitations: cost, controller dependency, overlay complexity.",
    tip: "The benefit is using ANY transport as one overlay; the limits are operational — cost and complexity.",
    steps: [
      {
        kind: "explain",
        title: "What you gain, what it costs",
        body: "Catalyst SD-WAN's headline benefit is transport independence: MPLS, broadband internet, and LTE all join one overlay, OMP picks the best path per prefix, and policy is centralized and consistent everywhere. The limitations are real too: controller subscriptions and hardware, a dependency on the overlay control plane, and the operational complexity of running an overlay on top of the existing network.",
      },
      {
        kind: "checkpoint",
        title: "Weigh the tradeoff",
        prompt: "Which statement about Catalyst SD-WAN benefits and limitations is correct?",
        options: [
          { value: "benefit-transport", title: "Transport independence + central control", note: "Any WAN joins; OMP picks the best path" },
          { value: "limit-complexity", title: "Complexity is a benefit", note: "Complexity is a limitation — not a win" },
          { value: "limit-no-overlay", title: "The overlay complexity is avoidable", note: "The overlay is the point — cost is the limit" },
        ],
        correct: "benefit-transport",
        explain: "Transport independence and centralized policy are the benefits; cost and complexity are the acknowledged limits.",
        wrongGuidance: "Keep the roles straight: complexity is SD-WAN's cost, not its benefit — and the overlay is the whole point of the product.",
      },
    ],
  },

  // ─── The Signal Detective (assurance toolset) ─────────────────────────────
  {
    id: "rescue-signal-diagnose",
    mission: "signal-detective",
    phases: ["diagnose"],
    isDefault: true,
    title: "The diagnostic ladder",
    teaches: "ping proves reachability, traceroute shows the path, show interface reveals link health, and a conditional debug names the exact culprit.",
    tip: "Back in the mission: on R-CORE run ping, traceroute, show interface gi0/1, then debug ip packet access-list 150 and confirm with show ip access-lists 150.",
    steps: [
      {
        kind: "explain",
        title: "The ladder",
        body: "Diagnose in order. ping proves basic reachability. traceroute shows the path and where it stops. show interface reveals link health — input errors, CRC, and load. When the interface is clean but traffic is still dying, a conditional debug (debug ip packet access-list 150) catches the packets as they are dropped, and show ip access-lists 150 shows the hit count that names the culprit.",
      },
      {
        kind: "checkpoint",
        title: "Read the evidence",
        prompt: "Ping succeeds, traceroute completes, but show interface gi0/1 shows heavy input errors and the debug output says dropped by ACL 150. What is happening?",
        options: [
          { value: "acl-drop", title: "ACL 150 is dropping the traffic", note: "The debug + hit count name it exactly" },
          { value: "link-down", title: "The link is down", note: "Line protocol is up — the link is fine" },
          { value: "no-route", title: "No route to the destination", note: "Ping and traceroute both succeed" },
        ],
        correct: "acl-drop",
        explain: "Reachability and the path are fine; the interface is clean-ish but the ACL hit count proves ACL 150 drops the app's UDP traffic.",
        wrongGuidance: "Ping and traceroute both succeed, so routing is fine — and the link is up. The debug names the ACL as the dropper.",
      },
      {
        kind: "cli",
        device: "R-CORE",
        prompt: "R-CORE#",
        title: "Name the culprit",
        command: "show ip access-lists 150",
        expectedOutput: "Extended IP access list 150\n    10 deny udp any any eq 9999 (48213 matches)",
        wrongHint: "In privileged EXEC on R-CORE: show ip access-lists 150",
        explain: "48,213 matches — ACL 150 has been silently dropping the app's UDP/9999 traffic.",
      },
    ],
  },
  {
    id: "rescue-signal-netflow",
    mission: "signal-detective",
    phases: ["flow"],
    isDefault: false,
    title: "Flexible NetFlow in one screen",
    teaches: "A flow record matches and counts, a flow exporter ships records to a collector, and the monitor binds them to an interface.",
    tip: "NetFlow counts flows and exports them (UDP 2055) — it never copies full packets; that is SPAN.",
    steps: [
      {
        kind: "explain",
        title: "Three pieces of Flexible NetFlow",
        body: "Flexible NetFlow has three building blocks. A flow record defines what to match (source/destination IP) and what to collect (byte and packet counters). A flow exporter ships the records to a collector over UDP (commonly 2055). A flow monitor binds the record and exporter, and is applied to an interface in the input direction.",
      },
      {
        kind: "checkpoint",
        title: "What NetFlow does",
        prompt: "The config exports records to 203.0.113.50 over UDP 2055. What is Flexible NetFlow actually doing?",
        options: [
          { value: "fnf-export", title: "Counting flows and exporting records", note: "To the collector at 203.0.113.50" },
          { value: "capture", title: "Copying full packets", note: "Full-packet copies are SPAN's job" },
          { value: "snmp", title: "Polling counters with SNMP", note: "NetFlow pushes; SNMP pulls" },
        ],
        correct: "fnf-export",
        explain: "Flexible NetFlow is accounting: it counts flows and exports the records for analysis.",
        wrongGuidance: "NetFlow counts, it does not copy packets (SPAN does), and it pushes records rather than polling like SNMP.",
      },
    ],
  },
  {
    id: "rescue-signal-span",
    mission: "signal-detective",
    phases: ["span"],
    isDefault: false,
    title: "SPAN in one screen",
    teaches: "A monitor session copies a source port to a destination port — the analyzer gets a full packet copy.",
    tip: "monitor session 1 source interface gi0/1 both, then destination interface gi0/2 — verify with show monitor session 1.",
    steps: [
      {
        kind: "explain",
        title: "Mirror, don't count",
        body: "SPAN (Switched Port Analyzer) copies real packets from a source port to a destination port where an analyzer listens. Unlike NetFlow's flow counters, SPAN gives you the full frames — payload and all. Local SPAN runs on one switch: session 1 sources gi0/1 in both directions and destines gi0/2.",
      },
      {
        kind: "checkpoint",
        title: "Pick the mirror",
        prompt: "You need the actual packets of a conversation for a capture. Which tool?",
        options: [
          { value: "span", title: "SPAN monitor session", note: "Copies full packets to the analyzer" },
          { value: "netflow", title: "Flexible NetFlow", note: "Counts flows — no payload" },
          { value: "snmp", title: "SNMP polling", note: "Counter data only" },
        ],
        correct: "span",
        explain: "SPAN copies full packets — exactly what a capture needs.",
        wrongGuidance: "NetFlow and SNMP give you counters, not packets. Only SPAN delivers the full frames.",
      },
      {
        kind: "cli",
        device: "R-CORE",
        prompt: "R-CORE(config)#",
        title: "Mirror the link",
        command: "monitor session 1 source interface gi0/1 both",
        expectedOutput: "Session 1 source ports: Gi0/1 (both directions)",
        wrongHint: "In global config on R-CORE: monitor session 1 source interface gi0/1 both",
        explain: "Session 1 now copies gi0/1 in both directions — add the destination port next.",
      },
    ],
  },
  {
    id: "rescue-signal-sla",
    mission: "signal-detective",
    phases: ["sla"],
    isDefault: false,
    title: "IP SLA in one screen",
    teaches: "IP SLA generates probe traffic (icmp-echo) on a schedule and reports RTT — a latency baseline you can threshold.",
    tip: "ip sla 10 → icmp-echo 203.0.113.1 → frequency 60 → ip sla schedule 10 life forever start-time now, then show ip sla statistics.",
    steps: [
      {
        kind: "explain",
        title: "Probe the path",
        body: "IP SLA makes the router generate test traffic. An operation (ip sla 10) sends icmp-echo probes to a target, a frequency sets the interval (60 seconds), and ip sla schedule starts it — here, forever. show ip sla statistics reports the RTT: latest, min, max, and success/failure counts.",
      },
      {
        kind: "checkpoint",
        title: "What IP SLA measures",
        prompt: "Probe 10 sends ICMP echo to 203.0.113.1 every 60 seconds. What does its statistics report?",
        options: [
          { value: "rtt", title: "Round-trip time to the target", note: "Plus min/max and success counts" },
          { value: "flows", title: "Flow records", note: "That is NetFlow" },
          { value: "packets", title: "Copied packets", note: "That is SPAN" },
        ],
        correct: "rtt",
        explain: "IP SLA measures RTT — the latency baseline for the path.",
        wrongGuidance: "IP SLA reports latency (RTT). Flow records are NetFlow; copied packets are SPAN.",
      },
      {
        kind: "cli",
        device: "R-EDGE",
        prompt: "R-EDGE(config)#",
        title: "Schedule the probe",
        command: "ip sla schedule 10 life forever start-time now",
        expectedOutput: "Probe 10 scheduled — running forever, starting now.",
        wrongHint: "In global config on R-EDGE, after defining ip sla 10: ip sla schedule 10 life forever start-time now",
        explain: "The probe now runs indefinitely — every 60 seconds, a fresh RTT measurement.",
      },
    ],
  },
  {
    id: "rescue-signal-controller",
    mission: "signal-detective",
    phases: ["controller", "netconf", "final-check"],
    isDefault: false,
    title: "Catalyst Center and programmability",
    teaches: "Cisco Catalyst Center's Assurance monitors health; its design/provision/compliance workflows push config. NETCONF (SSH/830) and RESTCONF (HTTPS/443) both speak YANG.",
    tip: "Assurance = monitoring. Design/provision/compliance = configuration. RESTCONF = YANG JSON over HTTPS.",
    steps: [
      {
        kind: "explain",
        title: "Controller vs. API",
        body: "Cisco Catalyst Center (formerly DNA Center) does two jobs. Its Assurance module is the monitoring side: health scores, insights, and troubleshooting. Its configuration side covers design templates, provisioning, and compliance checks against a golden config — increasingly through AI-powered workflows. Below the controller, NETCONF and RESTCONF give programmatic access to devices: NETCONF over SSH on port 830, RESTCONF over HTTPS on port 443, both exchanging YANG-modeled data as XML or JSON.",
      },
      {
        kind: "checkpoint",
        title: "Which workflow?",
        prompt: "A team pushes a design template to switches and then checks they match the golden config. Which Catalyst Center capability is that?",
        options: [
          { value: "design-comply", title: "Design, provision, compliance", note: "Configuration workflows" },
          { value: "assurance", title: "Assurance health monitoring", note: "That is the monitoring side" },
          { value: "ipsla", title: "IP SLA probes", note: "Those run on routers" },
        ],
        correct: "design-comply",
        explain: "Templates, provisioning, and compliance checks are the configuration side of Catalyst Center.",
        wrongGuidance: "Assurance is monitoring, and IP SLA runs on routers. Pushing and validating config is the design/provision/compliance workflow.",
      },
      {
        kind: "checkpoint",
        title: "Pick the API",
        prompt: "You fetched interface state as JSON over HTTPS from /restconf/data. What did you use?",
        options: [
          { value: "restconf", title: "RESTCONF over HTTPS (443)", note: "YANG data as JSON" },
          { value: "netconf", title: "NETCONF over SSH (830)", note: "The SSH sibling protocol" },
          { value: "cli", title: "Plain CLI", note: "The response was structured JSON" },
        ],
        correct: "restconf",
        explain: "RESTCONF serves YANG-modeled JSON/XML over HTTPS — exactly the GET you performed.",
        wrongGuidance: "NETCONF is SSH/830 and CLI is unstructured — the JSON-over-HTTPS response is RESTCONF.",
      },
    ],
  },

  {
    id: "rescue-edge-pbr",
    mission: "edge",
    phases: ["pbr", "local"],
    isDefault: false,
    title: "Routing with opinions",
    teaches: "PBR overrides the destination lookup for matched traffic; ip local policy covers the router's own traffic.",
    tip: "Interface policy for transit, ip local policy for the router's own flows.",
    steps: [
      {
        kind: "explain",
        title: "PBR overrides",
        body: "A route-map with match + set ip next-hop is PBR. It runs before the destination-based lookup and sends matched traffic to the chosen next hop — without touching the routing table. It is applied inbound on an interface.",
      },
      {
        kind: "checkpoint",
        title: "What PBR does",
        prompt: "ip policy route-map PREFER-ISP1 is applied on R-EDGE Gi0/1. What does it do to matching traffic?",
        options: [
          { value: "overrides", title: "Overrides the route lookup", note: "Matched traffic takes the set next-hop" },
          { value: "changes-table", title: "Rewrites the routing table", note: "PBR never changes the RIB" },
          { value: "local-only", title: "Only the router's own traffic", note: "An interface policy covers transit too" },
        ],
        correct: "overrides",
        explain: "PBR intercepts matched traffic before the lookup and sends it to the configured next-hop — the RIB is untouched.",
        wrongGuidance: "PBR redirects traffic, it does not rewrite the routing table — and an interface policy covers transit traffic, not just local.",
      },
      {
        kind: "checkpoint",
        title: "The router's own traffic",
        prompt: "To also steer traffic the router itself generates, which command applies the same route-map?",
        options: [
          { value: "local-policy", title: "ip local policy route-map PREFER-ISP1", note: "Global policy for locally sourced traffic" },
          { value: "outbound-policy", title: "ip policy route-map on the egress", note: "PBR is inbound only" },
          { value: "default-route", title: "A default route to 198.51.100.1", note: "Not PBR — it changes path selection" },
        ],
        correct: "local-policy",
        explain: "ip local policy extends the route-map to locally generated traffic — interface policies only catch transit.",
        wrongGuidance: "PBR evaluates inbound traffic, so there is no outbound interface policy; a default route is not PBR. Locally sourced flows need ip local policy.",
      },
    ],
  },

  // ─── Lock the Control Plane (auth / AAA / iACL / CoPP / API / design) ─────
  {
    id: "rescue-lock-access",
    mission: "lock-the-control-plane",
    phases: ["local", "aaa"],
    isDefault: true,
    title: "Device access and AAA",
    teaches: "Local auth = username with a secret + login local + SSH-only VTY lines; AAA centralizes identity with a RADIUS/TACACS+ server and method lists.",
    tip: "Back in the mission: on R-BR create the user, lock line vty 0 4, then aaa new-model with radius server ISE and verify with show aaa servers.",
    steps: [
      {
        kind: "explain",
        title: "Lock the door first",
        body: "Device access starts with the VTY lines. A real user needs username NAME secret — the secret keyword stores the password hashed, a plain password does not. The VTY lines must run login local to authenticate against that local database, and transport input ssh to lock out Telnet entirely. Verify with show running-config | include line vty.",
      },
      {
        kind: "cli",
        device: "R-BR",
        prompt: "R-BR(config)#",
        title: "Create the user",
        command: "username admin secret C1scoBranch!",
        expectedOutput: "Local user admin created with a secret (encrypted in the config).",
        wrongHint: "In global config on R-BR: username admin secret C1scoBranch!",
        explain: "The secret keyword stores the password hashed — never a plaintext password.",
      },
      {
        kind: "explain",
        title: "Then centralize",
        body: "One router's local database is still a single point of management. AAA moves authentication to a server: aaa new-model turns it on, radius server defines the ISE server with its address and shared key, and aaa authentication login default group radius local tries RADIUS first and falls back to local if it is unreachable.",
      },
      {
        kind: "checkpoint",
        title: "Why AAA?",
        prompt: "The branch wants one identity store for all routers instead of separate local databases. Which piece makes that possible?",
        options: [
          { value: "aaa-radius", title: "AAA with a RADIUS server", note: "Centralized authentication + fallback" },
          { value: "login-local", title: "login local on every router", note: "Still per-device databases" },
          { value: "transport-ssh", title: "transport input ssh", note: "That only blocks Telnet" },
        ],
        correct: "aaa-radius",
        explain: "AAA with a RADIUS/TACACS+ server centralizes the identity store — method lists let it fall back to local.",
        wrongGuidance: "login local and SSH-only are per-device hardening — centralizing the store is what AAA + RADIUS does.",
      },
    ],
  },
  {
    id: "rescue-lock-edge",
    mission: "lock-the-control-plane",
    phases: ["iacl", "copp"],
    isDefault: false,
    title: "iACL and CoPP",
    teaches: "An infrastructure ACL filters who may reach the device; CoPP polices how much control-plane traffic the CPU must process.",
    tip: "iACL = who can reach me (inbound on external interfaces). CoPP = rate-limit the control plane (police, drop excess).",
    steps: [
      {
        kind: "explain",
        title: "Two defenses for the device itself",
        body: "An infrastructure ACL (iACL) is applied inbound on external interfaces: it permits only the management and control flows the router must accept — routing peers, SSH/NTP from the management network — and denies everything else aimed at the device. Transit traffic that merely crosses the router still flows normally. CoPP is different: a policy-map type control plane with police rates the matched classes of traffic destined to the control plane, dropping what exceeds the rate before it can burn CPU.",
      },
      {
        kind: "checkpoint",
        title: "Pick the iACL role",
        prompt: "An infrastructure ACL is placed inbound on the WAN interface. What does it do?",
        options: [
          { value: "filter-device", title: "Filters traffic aimed at the device", note: "Permits mgmt/control flows, denies the rest" },
          { value: "filter-transit", title: "Filters traffic crossing the router", note: "Transit traffic is not the iACL's job" },
          { value: "encrypt", title: "Encrypts management sessions", note: "That is SSH/IPsec, not an ACL" },
        ],
        correct: "filter-device",
        explain: "The iACL protects the infrastructure itself: only the allowed management and control flows reach the device.",
        wrongGuidance: "Transit traffic still flows — the iACL filters what is allowed to reach the router's own addresses.",
      },
      {
        kind: "checkpoint",
        title: "What CoPP does",
        prompt: "Which statement about Control Plane Policing (CoPP) is correct?",
        options: [
          { value: "police-cp", title: "Polices traffic destined to the control plane", note: "Rates matched classes, drops excess" },
          { value: "blocks-mgmt", title: "Blocks all management traffic", note: "Management classes are admitted at a rate" },
          { value: "replaces-acl", title: "Replaces the infrastructure ACL", note: "ACL filters reach; CoPP rates the CPU load" },
        ],
        correct: "police-cp",
        explain: "CoPP attaches to the control plane and polices its input — excess is dropped before it can exhaust the CPU.",
        wrongGuidance: "CoPP admits management traffic (at a rate) and does not replace the iACL — the two work together.",
      },
    ],
  },
  {
    id: "rescue-lock-api",
    mission: "lock-the-control-plane",
    phases: ["rest", "design"],
    isDefault: false,
    title: "REST security and defense in depth",
    teaches: "REST APIs need TLS + API keys/tokens + role-based auth; endpoint security, NGFW, TrustSec (SGTs), and MACsec (L2) each cover a layer.",
    tip: "REST: HTTPS + API keys + roles. Design: endpoint (NAC/AV) → NGFW (apps) → TrustSec (SGT tags) → MACsec (links).",
    steps: [
      {
        kind: "explain",
        title: "APIs need their own locks",
        body: "A REST API is a remote-control channel for your network — if it is open, so is the network. Security means TLS (HTTPS) everywhere, authenticating every call with API keys or tokens, authorizing by role, rate limiting, and validating input. Plaintext or wide-open APIs leak credentials and invite replay.",
      },
      {
        kind: "checkpoint",
        title: "Secure the API",
        prompt: "The branch will be managed via REST. Which security baseline is correct?",
        options: [
          { value: "tls-keys", title: "HTTPS + API keys + role-based auth", note: "Encrypt, authenticate, authorize" },
          { value: "plaintext", title: "Plaintext over the LAN is fine", note: "Credentials travel in clear — a leak" },
          { value: "open-api", title: "An open API with no auth", note: "An unauthenticated control channel" },
        ],
        correct: "tls-keys",
        explain: "TLS encrypts, API keys/tokens authenticate, roles authorize — the REST security baseline.",
        wrongGuidance: "Plaintext and open APIs are exactly the holes this mission closes — every call needs TLS and authentication.",
      },
      {
        kind: "checkpoint",
        title: "The layered design",
        prompt: "Which statement correctly describes the layered security design (5.4.a–d)?",
        options: [
          { value: "layered", title: "Endpoint + NGFW + TrustSec + MACsec", note: "Each layer covers the one below it" },
          { value: "macsec-l3", title: "MACsec replaces the firewall", note: "MACsec encrypts L2 links only" },
          { value: "trustsec-8021x", title: "TrustSec is an 802.1X protocol", note: "TrustSec enforces with SGT tags" },
        ],
        correct: "layered",
        explain: "Defense in depth: NAC/AV on endpoints, application inspection at the NGFW, SGT-tagged policy with TrustSec, and L2 encryption with MACsec.",
        wrongGuidance: "MACsec is Layer 2 and TrustSec uses SGTs — the layers complement each other instead of replacing one another.",
      },
    ],
  },

  // ─── Automator Prime (Python / JSON / YANG / APIs / EEM / orchestration) ──
  {
    id: "rescue-automator-code",
    mission: "automator-prime",
    phases: ["python", "json"],
    isDefault: true,
    title: "Python + JSON for the APIs",
    teaches: "Python's requests library drives RESTCONF/REST APIs; every JSON payload you send is validated against a YANG model.",
    tip: "Back in the mission: import requests, send the GET to /restconf/data/interfaces, then construct the ietf-interfaces envelope and the SD-WAN Manager device payload.",
    steps: [
      {
        kind: "explain",
        title: "The script is the engineer",
        body: "Automation replaces hands-on CLI with code. Python's requests library sends the HTTP calls: a GET against /restconf/data/interfaces returns the device's YANG-modeled data as JSON. The payloads you construct must be valid JSON AND match the YANG model the endpoint expects — that is why the envelope is ietf-interfaces:interfaces, not anything you invent.",
      },
      {
        kind: "cli",
        device: "WORKSTATION",
        prompt: ">>>",
        title: "Load the HTTP client",
        command: "import requests",
        expectedOutput: "requests loaded — the HTTP client for RESTCONF calls.",
        wrongHint: "At the Python prompt on the workstation: import requests",
        explain: "requests is the library every RESTCONF/REST probe starts with.",
      },
      {
        kind: "checkpoint",
        title: "Why the exact envelope?",
        prompt: "Why must the JSON payload use ietf-interfaces:interfaces rather than any structure you invent?",
        options: [
          { value: "yang-match", title: "It must match the YANG model", note: "Payloads are validated against the data model" },
          { value: "any-json", title: "Any valid JSON is accepted", note: "Valid syntax is not enough — structure matters" },
          { value: "xml-only", title: "RESTCONF only accepts XML", note: "RESTCONF speaks JSON too" },
        ],
        correct: "yang-match",
        explain: "RESTCONF validates every payload against the endpoint's YANG model — the structure must match, not just the syntax.",
        wrongGuidance: "Valid JSON syntax alone is not enough — the endpoint validates the structure against YANG, and RESTCONF accepts JSON.",
      },
    ],
  },
  {
    id: "rescue-automator-yang",
    mission: "automator-prime",
    phases: ["yang"],
    isDefault: false,
    title: "YANG data models",
    teaches: "YANG models network data as a tree of containers, lists, and leaves — the schema behind every RESTCONF payload.",
    tip: "Containers group, lists repeat, leaves hold values — that tree is the model your JSON must match.",
    steps: [
      {
        kind: "explain",
        title: "The schema behind the API",
        body: "YANG is a data modeling language. A module defines the SHAPE of configuration and state data as a tree: containers group related data, lists hold repeating entries (like the interface list), and leaves hold the actual values (name, enabled). The model is independent of encoding — JSON and XML both carry it.",
      },
      {
        kind: "checkpoint",
        title: "What YANG is",
        prompt: "Which statement correctly describes YANG?",
        options: [
          { value: "data-tree", title: "Models data as a tree of containers, lists, leaves", note: "The schema validated against" },
          { value: "script", title: "A scripting language for devices", note: "YANG describes data, it never executes" },
          { value: "cli-format", title: "A CLI configuration format", note: "YANG is encoding-independent" },
        ],
        correct: "data-tree",
        explain: "YANG defines the data tree — modules with containers, lists, and leaves that payloads must match.",
        wrongGuidance: "YANG describes data, it does not script — and it is not a CLI format, it is the schema behind the API.",
      },
    ],
  },
  {
    id: "rescue-automator-apis",
    mission: "automator-prime",
    phases: ["apis", "rest"],
    isDefault: false,
    title: "Controllers and responses",
    teaches: "Cisco Catalyst Center (formerly DNA Center) and SD-WAN Manager (formerly vManage) are REST APIs over HTTPS (SD-WAN Manager: /dataservice/ + X-XSRF-TOKEN); status codes tell you the outcome — 201 means the resource was created.",
    tip: "SD-WAN Manager = /dataservice/ + X-XSRF-TOKEN header. 2xx success, 4xx your request, 5xx the server.",
    steps: [
      {
        kind: "explain",
        title: "Call the controller, not the box",
        body: "Cisco Catalyst Center (formerly DNA Center) and SD-WAN Manager (formerly vManage) expose REST APIs over HTTPS. An SD-WAN Manager call looks like GET /dataservice/device with an X-XSRF-TOKEN header for session security — your script exchanges JSON, the controller does the heavy lifting. The status code tells you the outcome before you read the payload.",
      },
      {
        kind: "checkpoint",
        title: "Read the status code",
        prompt: "The PUT that created Loopback100 returned 201 Created. What does 201 mean?",
        options: [
          { value: "created", title: "The resource was created", note: "A successful create — 2xx" },
          { value: "missing", title: "404 — the URL is missing", note: "That is a not-found, not a create" },
          { value: "server-fault", title: "500 — the server crashed", note: "That is a server-side failure" },
        ],
        correct: "created",
        explain: "201 Created is the success code for a PUT that creates — 4xx means your request, 5xx means the server.",
        wrongGuidance: "404 is a missing resource and 500 is a server fault — a successful create returns 201.",
      },
    ],
  },
  {
    id: "rescue-automator-eem",
    mission: "automator-prime",
    phases: ["eem"],
    isDefault: false,
    title: "EEM applets on the box",
    teaches: "EEM runs automation inside the device: event manager applet defines it, event syslog pattern triggers it, action ... cli command does the work.",
    tip: "Back in the mission: event manager applet save-config → event syslog pattern \"CONFIG_I\" → action 1.0/2.0 cli command \"enable\" and \"write memory\".",
    steps: [
      {
        kind: "explain",
        title: "Automation without a controller",
        body: "EEM (Embedded Event Manager) runs scripts inside the device itself. An applet has three parts: event manager applet NAME defines it, an event (here event syslog pattern \"CONFIG_I\") picks when it fires, and action lines run CLI commands. The classic config-save applet: on any config change, enter privileged mode and write memory.",
      },
      {
        kind: "cli",
        device: "R-CORE",
        prompt: "R-CORE(config)#",
        title: "Define the applet",
        command: "event manager applet save-config",
        expectedOutput: "Applet save-config defined — add its event and actions.",
        wrongHint: "In global config on R-CORE: event manager applet save-config",
        explain: "The applet header comes first; the event and actions follow under it.",
      },
      {
        kind: "checkpoint",
        title: "When it fires",
        prompt: "The applet uses event syslog pattern \"CONFIG_I\". When does it run?",
        options: [
          { value: "config-change", title: "On config-change syslog messages", note: "CONFIG_I marks a config change" },
          { value: "boot-time", title: "Only at boot", note: "That would be an applet with no useful event" },
          { value: "on-timer", title: "On a schedule", note: "This applet has no timer" },
        ],
        correct: "config-change",
        explain: "The CONFIG_I syslog pattern fires the applet every time the configuration changes.",
        wrongGuidance: "The pattern matches config-change syslog messages — not boot or a timer.",
      },
    ],
  },
  {
    id: "rescue-automator-agent",
    mission: "automator-prime",
    phases: ["agent"],
    isDefault: false,
    title: "Agent vs agentless",
    teaches: "Agentless orchestration drives devices over SSH/WinRM with nothing installed; agent-based tools install software on every managed device.",
    tip: "Agentless = SSH/WinRM, nothing on the box. Agent = software installed on each managed device.",
    steps: [
      {
        kind: "explain",
        title: "Two ways to drive the fleet",
        body: "Agentless orchestration tools (Ansible is the classic example) connect to devices over SSH or WinRM and push config without installing anything on the target — fast onboarding, nothing to patch on the box. Agent-based tools install software (the agent) on every managed device; the agent collects data and executes locally, which adds overhead but enables local telemetry.",
      },
      {
        kind: "checkpoint",
        title: "Pick the contrast",
        prompt: "Which statement correctly contrasts agent and agentless orchestration?",
        options: [
          { value: "agentless-ssh", title: "Agentless = SSH/WinRM, nothing installed", note: "Agent = software on each device" },
          { value: "agentless-install", title: "Agentless = software on every device", note: "That is the agent model, reversed" },
          { value: "agent-clean", title: "Agent-based = nothing on the target", note: "The agent IS the installed software" },
        ],
        correct: "agentless-ssh",
        explain: "Agentless connects over SSH/WinRM with nothing on the target; agent-based installs software on each device.",
        wrongGuidance: "Keep the roles straight: installing software is the agent model — agentless tools connect over SSH/WinRM with nothing installed.",
      },
    ],
  },
];

/**
 * Finds the rescue for a main mission and phase: exact phase match first, then
 * the mission's default rescue, then any rescue for the mission.
 */
export function rescueFor(mission: string, phase?: string): RescueDefinition | null {
  if (phase) {
    const exact = RESCUES.find((rescue) => rescue.mission === mission && rescue.phases.includes(phase));
    if (exact) return exact;
  }
  const fallback = RESCUES.find((rescue) => rescue.mission === mission && rescue.isDefault);
  return fallback ?? RESCUES.find((rescue) => rescue.mission === mission) ?? null;
}
